#ifndef __ACL_BTS_CUSTOM_H__
#define __ACL_BTS_CUSTOM_H__

#define ACL_OPT_CUSTOM \

#define ACL_OPT_ARRAY  \

#define ACL_CNT_CUSTOM   \
    ACL_PKTS, \
    ACL_REDIR_PKTS, \
    ACL_REDIR_DROP_GET_OR_POST, \
    ACL_REDIR_LONG_URI_DROP, \
    ACL_REDIR_DROP_HEAD_GEN1, \
    ACL_REDIR_DROP_SEND_PACKET, \
    ACL_REDIR_TX_SUCCESS,\
    \
    /* ADP Module */ \
    URL_HOMEPAGE,\
    ADP_IPKTS, \
    ADP_DROP_PARAM, \
    ADP_DROP_GET_OR_POST, \
    ADP_DROP_121ZOU, \
    ADP_DROP_NOT_HAO123, \
    ADP_DROP_ACT_PUSH, \
    ADP_DROP_ACT_DROP,\
    ADP_DROP_OUR_SUFFIX, \
    ADP_DROP_BACKSLASH_SUFFIX, \
    ADP_DROP_HTML_SUFFIX, \
    ADP_DROP_ADP_INTERVAL, \
    ADP_DROP_HEAD_GEN1, \
    ADP_DROP_SEND_PACKET1, \
    ADP_DROP_HEAD_GEN2, \
    ADP_DROP_SEND_PACKET2, \
    ADP_DROP_PUSH_PC, \
    ADP_DROP_PUSH_MOBILE, \
    ADP_PUSH_PC, \
    ADP_PUSH_MOBILE, \
    ADP_ALL_CAN_PUSH,\
	ADP_PUSH_TX_SUCCESS, \
	ADP_PUSH_ACK_SUCCESS, \
    ADP_HAO123,

#define ACL_CNT_DEF_CUSTOM   \
    CNT_DEF(ACL_PKTS), \
    CNT_DEF(ACL_REDIR_PKTS), \
    CNT_DEF(ACL_REDIR_DROP_GET_OR_POST), \
    CNT_DEF(ACL_REDIR_LONG_URI_DROP), \
    CNT_DEF(ACL_REDIR_DROP_HEAD_GEN1), \
    CNT_DEF(ACL_REDIR_DROP_SEND_PACKET), \
    CNT_DEF(ACL_REDIR_TX_SUCCESS), \
    \
    /* ADP Module */ \
    CNT_DEF(URL_HOMEPAGE),\
    CNT_DEF(ADP_IPKTS), \
    CNT_DEF(ADP_DROP_PARAM), \
    CNT_DEF(ADP_DROP_GET_OR_POST), \
    CNT_DEF(ADP_DROP_121ZOU), \
    CNT_DEF(ADP_DROP_NOT_HAO123), \
    CNT_DEF(ADP_DROP_ACT_PUSH), \
    CNT_DEF(ADP_DROP_ACT_DROP),\
    CNT_DEF(ADP_DROP_OUR_SUFFIX), \
    CNT_DEF(ADP_DROP_BACKSLASH_SUFFIX), \
    CNT_DEF(ADP_DROP_HTML_SUFFIX), \
    CNT_DEF(ADP_DROP_ADP_INTERVAL), \
    CNT_DEF(ADP_DROP_HEAD_GEN1), \
    CNT_DEF(ADP_DROP_SEND_PACKET1), \
    CNT_DEF(ADP_DROP_HEAD_GEN2), \
    CNT_DEF(ADP_DROP_SEND_PACKET2), \
    CNT_DEF(ADP_DROP_PUSH_PC), \
    CNT_DEF(ADP_DROP_PUSH_MOBILE), \
    CNT_DEF(ADP_PUSH_PC), \
    CNT_DEF(ADP_PUSH_MOBILE), \
    CNT_DEF(ADP_ALL_CAN_PUSH),\
	CNT_DEF(ADP_PUSH_TX_SUCCESS), \
	CNT_DEF(ADP_PUSH_ACK_SUCCESS), \
    CNT_DEF(ADP_HAO123),

#endif
